---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple echo Lambda Function

Resources:  
  EchoLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./code
      Handler: lambda_function.lambda_handler
      Runtime: python3.7

Outputs:
  EchoLambdaArn:
    Description: ARN of the Echo Lambda Function
    Value: !GetAtt EchoLambda.Arn
